# Generated by Django 4.2.5 on 2024-11-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_timestamp',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_timestamp',
            new_name='start_date_time',
        ),
    ]
